name: Rail Service Weekly Export + Email

on:
  workflow_dispatch:    # allow manual trigger
  schedule:
    # Thursdays 11:00 AM ET -> 15:00 UTC (EDT) / 16:00 UTC (EST)
    - cron: '0 15 * * 4'
    - cron: '0 16 * * 4'

jobs:
  run-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check Eastern time (only run at 11:00 ET)
        id: timecheck
        run: |
          python - <<'PY'
          import os
          from datetime import datetime
          from zoneinfo import ZoneInfo
          now = datetime.now(ZoneInfo("America/New_York"))
          should = (now.weekday() == 3 and now.hour == 11)  # Thursday 11am ET
          print(f"Now in ET: {now.isoformat()} -> should_run={should}")
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              fh.write(f"should_run={'true' if should else 'false'}\n")
          PY

      - name: Set up Python
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript python3-tk python3-opencv libgl1 libglib2.0-0 libsm6 libxrender1 libxext6
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas openpyxl xlsxwriter pdfplumber

      - name: Run aar_data.py
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: python aar_data.py

      - name: Create zip bundle (Excel + PDF)
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        run: |
          ZIP_NAME="rail_service_excels_$(date +'%Y-%m-%d_%a').zip"
          zip "$ZIP_NAME" *.xlsx *.pdf || echo "⚠️ No Excel/PDF files to zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload zip artifact
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_NAME }}
          retention-days: 14

      - name: Email zip result
        if: ${{ steps.timecheck.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.yahoo.com
          server_port: 465
          secure: true
          username: ${{ secrets.YAHOO_EMAIL }}
          password: ${{ secrets.YAHOO_APP_PASSWORD }}
          from: ${{ secrets.YAHOO_EMAIL }}
          to: ${{ secrets.TO_EMAIL }}
          subject: "Rail Service Export – ${{ github.repository }} – ${{ env.ZIP_NAME }}"
          body: |
            Attached is the weekly Rail Service export bundle.
            Repo: ${{ github.repository }}
            Run ID: ${{ github.run_id }}
            Commit: ${{ github.sha }}
          attachments: ${{ env.ZIP_NAME }}
