name: Download Rail Service Excels

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run aar_data.py
        run: python aar_data.py

      - name: List downloaded Excel files
        run: ls -lh *.xlsx || echo "⚠️ No Excel files found"

      - name: Set artifact name with date
        run: echo "ARTIFACT_NAME=rail_service_excels_$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload Excel artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: "*.xlsx"
