name: FRED monthly/weekly pull

on:
  workflow_dispatch: {}       # allow manual runs
  schedule:
    # Every Sunday at 14:00 UTC (≈ 9:00/10:00am ET depending on DST)
    - cron: "0 14 * * 0"
    # On the 20th of each month at 14:00 UTC
    - cron: "0 14 20 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FRED pull
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python pull_fred_series_bulk_split_pivot_adaptive.py

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: fred_series_${{ github.run_number }}
          path: fred_series_2019base.xlsx
          if-no-files-found: error
